version: '3'
services:
  controller:
    build: ./controller
    privileged: true
    volumes:
      - "./ansible:/ansible"
    working_dir: /ansible
  target:
    build: ./target
    privileged: true
